-- Migration 041: Institution-scoped editable email templates

CREATE TABLE IF NOT EXISTS public.email_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  institution_id UUID NOT NULL REFERENCES public.institutions(id) ON DELETE CASCADE,
  slug TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL CHECK (category IN ('system', 'custom')),
  system_type TEXT CHECK (system_type IN ('certificate', 'assignment')),
  subject_template TEXT NOT NULL,
  body_html_template TEXT NOT NULL,
  created_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT email_templates_slug_unique UNIQUE (institution_id, slug),
  -- NOTE: must not be named email_templates_system_type_check — that name is
  -- auto-generated by the column-level CHECK on system_type and would collide.
  CONSTRAINT email_templates_system_type_consistency CHECK (
    (category = 'system' AND system_type IS NOT NULL)
    OR (category = 'custom' AND system_type IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_email_templates_institution_id ON public.email_templates(institution_id);
CREATE INDEX IF NOT EXISTS idx_email_templates_system_type ON public.email_templates(institution_id, system_type)
  WHERE system_type IS NOT NULL;

ALTER TABLE public.email_templates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can manage email templates" ON public.email_templates;
CREATE POLICY "Admins can manage email templates" ON public.email_templates
  FOR ALL USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- Seed default system templates for GANSID + SCAGO (body = inner HTML; layout wrapper applied at send time)
INSERT INTO public.email_templates (
  institution_id, slug, name, description, category, system_type, subject_template, body_html_template
)
SELECT
  i.id,
  v.slug,
  v.name,
  v.description,
  'system',
  v.system_type,
  v.subject_template,
  v.body_html_template
FROM public.institutions i
CROSS JOIN (
  VALUES
    (
      'certificate',
      'Certificate issued',
      'Sent when a learner earns a course or program certificate',
      'certificate',
      'Your certificate for {{title}}',
      $body$
<h1 style="margin:0 0 16px;color:#0F172A;font-size:22px;">Congratulations! 🎉</h1>
<p style="margin:0 0 12px;color:#334155;font-size:15px;line-height:24px;">{{greeting}}</p>
<p style="margin:0 0 12px;color:#334155;font-size:15px;line-height:24px;">
  You have completed the {{kind}} <strong>{{title}}</strong> and earned your certificate.
</p>
<p style="margin:0 0 4px;color:#64748B;font-size:13px;">Certificate number</p>
<p style="margin:0 0 8px;color:#0F172A;font-size:16px;font-weight:bold;letter-spacing:1px;">{{certificateNumber}}</p>
<p style="margin:24px 0;"><a href="{{certificatesUrl}}" style="display:inline-block;padding:12px 28px;background-color:{{buttonColor}};color:#FFFFFF;font-size:14px;font-weight:bold;text-decoration:none;border-radius:8px;">View your certificate</a></p>
<p style="margin:0;color:#94A3B8;font-size:12px;line-height:18px;">
  Anyone can verify this certificate at <a href="{{verifyUrl}}" style="color:{{primaryColor}};">{{verifyUrl}}</a>
</p>
$body$
    ),
    (
      'assignment',
      'Course assigned',
      'Sent when an admin assigns a course to a learner',
      'assignment',
      'New course assigned: {{courseTitle}}',
      $body$
<h1 style="margin:0 0 16px;color:#0F172A;font-size:22px;">A course has been assigned to you</h1>
<p style="margin:0 0 12px;color:#334155;font-size:15px;line-height:24px;">{{greeting}}</p>
<p style="margin:0 0 12px;color:#334155;font-size:15px;line-height:24px;">
  <strong>{{courseTitle}}</strong> is now available in your {{institutionName}} learning portal.
</p>
{{dueDateBlock}}
<p style="margin:24px 0;"><a href="{{courseUrl}}" style="display:inline-block;padding:12px 28px;background-color:{{buttonColor}};color:#FFFFFF;font-size:14px;font-weight:bold;text-decoration:none;border-radius:8px;">Start learning</a></p>
$body$
    )
) AS v(slug, name, description, system_type, subject_template, body_html_template)
WHERE i.slug IN ('gansid', 'scago')
ON CONFLICT (institution_id, slug) DO NOTHING;
